# docker-compose.yml
version: "3.9"

services:
  neo4j:
    image: neo4j:5.22
    environment:
      - NEO4J_AUTH=neo4j/test1234
    ports: ["7474:7474","7687:7687"]
    volumes:
      - neo4j_data:/data
      - ./data/medical_dummy:/var/lib/neo4j/import

  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes: [qdrant_storage:/qdrant/storage]

  api:
    build: ./api
    environment:
      - QDRANT_URL=http://qdrant:6333
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes: ["./api:/app","./models:/models","./data:/data"]
    ports: ["8000:8000"]
    depends_on: [neo4j, qdrant]

  ui:
    build: ./ui
    ports: ["8501:8501"]
    volumes: ["./ui:/app","./data:/data"]
    depends_on: [api]

volumes:
  neo4j_data: {}
  qdrant_storage: {}
